[font]
# normal = {family = "JuliaMono", style = "Regular"}
# bold = {family = "JuliaMono", style = "Bold"}
# italic = {family = "JuliaMono", style = "Italic"}
normal = {family = "SFMono Nerd Font Mono", style = "Regular"}
bold = {family = "SFMono Nerd Font Mono", style = "Bold"}
italic = {family = "SFMono Nerd Font Mono", style = "Italic"}
size = 13

[env]
TERM = "xterm-256color"
