[font]
normal = {family = "Iosevka Nerd Font", style = "Regular"}
bold = {family = "Iosevka Nerd Font", style = "Bold"}
italic = {family = "Iosevka Nerd Font", style = "Italic"}
size = 13

[env]
TERM = "xterm-256color"
