[font]
# normal = {family = "FiraCode Nerd Font", style = "Regular"}
# bold = {family = "FiraCode Nerd Font", style = "Bold"}
# italic = {family = "FiraCode Nerd Font", style = "Italic"}
normal = {family = "Iosevka Nerd Font", style = "Regular"}
bold = {family = "Iosevka Nerd Font", style = "Bold"}
italic = {family = "Iosevka Nerd Font", style = "Italic"}
size = 12

[env]
TERM = "xterm-256color"

# [window]
# padding.x = 9
# padding.y = 9
