[font]
normal = {family = "Iosevka Nerd Font", style = "Regular"}
bold = {family = "Iosevka Nerd Font", style = "Bold"}
italic = {family = "Iosevka Nerd Font", style = "Italic"}
size = 14

[env]
TERM = "xterm-256color"

# [colors.primary]
# background = "#09363B"
# foreground = "#bdb395"
