[font]
normal = {family = "JuliaMono", style = "Regular"}
bold = {family = "JuliaMono", style = "Bold"}
italic = {family = "JuliaMono", style = "Italic"}
# normal = {family = "Iosevka Nerd Font Mono", style = "Regular"}
# bold = {family = "Iosevka Nerd Font Mono", style = "Bold"}
# italic = {family = "Iosevka Nerd Font Mono", style = "Italic"}
size = 10

[env]
TERM = "xterm-256color"

[general]
import = ["nord.toml"]
