-- local M = {}
--
-- function M.setup()
--   vim.cmd.colorscheme("rose-pine")
--
--   local function switch_colorscheme(name)
--     if vim.g.colors_name ~= name then
--       vim.cmd.colorscheme("" .. name)
--     end
--   end
--
--   vim.api.nvim_create_autocmd("FileType", {
--     pattern = { "tex", "plaintex", "latex" },
--     callback = function ()
--       switch_colorscheme("nord")
--     end,
--   })
-- end
--
-- return M
