#! /bin/sh

pkill -f "bspc subscribe monitor"
pgrep -x sxhkd > /dev/null || sxhkd &

# setup monitors
setup_monitors() {
    if [ "$#" -eq 1 ]; then  
        xrandr --output "$1" --auto
        bspc monitor "$1" -d  1 2 3 4 5 6 7 8 9 10
    else
        bspc monitor "$1" -d  1 2 3 4 5 6 7 8 9 10
        ~/bin/select-display.sh
    fi
}

init() {
    monitors=$(xrandr --query | awk '/ connected / {print $1}')
    setup_monitors "${monitors[@]}"
}

init

# ~/.config/polybar/launch.sh &
polybar example &


bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
