#!/usr/bin/env bash

ROFI_THEME="$HOME/dotfiles/rofi/black-white-selector.rasi"


SEMESTER=$(echo -e "2\n1" | rofi -dmenu -i -p "semester" -theme "$ROFI_THEME")
[ -z "$SEMESTER" ] && exit 0


BASE_DIR="$HOME/uni/bachelor-1/semester-$SEMESTER"
[ ! -d "$BASE_DIR" ] && rofi -e "Semester path not found: $BASE_DIR" && exit 1


COURSES=($(find "$BASE_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort))
COURSES+=("planning")
[ ${#COURSES[@]} -eq 0 ] && rofi -e "No courses found in $BASE_DIR" && exit 1


COURSE=$(printf "%s\n" "${COURSES[@]}" | rofi -dmenu -i -p "Course" -theme "$ROFI_THEME")
[ -z "$COURSE" ] && exit 0


if [[ "$COURSE" == "planning" ]]; then
    PDF_FILE="$BASE_DIR/planning.pdf"
    if [ -f "$PDF_FILE" ]; then
        $PDF_VIEWER "$PDF_FILE"
    else
        rofi -e "No planning.pdf found in $BASE_DIR"
    fi
    exit 0
fi


COURSE_PATH="$BASE_DIR/$COURSE"


SUBDIRS=($(find "$COURSE_PATH" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;))

SUBDIR=$(printf "%s\n" "${SUBDIRS[@]}" | rofi -dmenu -i -p "Option" -theme "$ROFI_THEME")
[ -z "$SUBDIR" ] && exit 0

FINAL_PATH="$COURSE_PATH/$SUBDIR"


# Sort pdfs by date
# mapfile -t PDFS < <(find "$FINAL_PATH" -maxdepth 1 -type f -iname "*.pdf" -printf "%T@ %p\n" | sort -nr | cut -d ' ' -f2 -)
mapfile -t PDFS < <(find "$FINAL_PATH" -maxdepth 1 -type f -iname "*.pdf" | sort)

if [ ${#PDFS[@]} -eq 0 ]; then
    rofi -e "No pdf files found in $FINAL_PATH"
    exit 1

elif [ ${#PDFS[@]} -eq 1 ]; then
    $PDF_VIEWER "${PDFS[0]}"
    exit 0

else
    CHOICES=()
    for FILE in "${PDFS[@]}"; do
        NAME=$(basename "$FILE" .pdf)
        DATE=$(date -r "$FILE" "+%d-%m-%Y")
        CHOICES+=("$NAME ($DATE)")
    done

    CHOSEN_DISPLAY=$(printf "%s\n" "${CHOICES[@]}" | rofi -dmenu -i -p "Choose pdf" -theme "$ROFI_THEME")
    [ -z "$CHOSEN_DISPLAY" ] && exit 0

    CHOSEN_FILE=$(echo "$CHOSEN_DISPLAY" | sed 's/ ([0-9]\{2\}-[0-9]\{2\}-[0-9]\{4\})$//')
    $PDF_VIEWER "$FINAL_PATH/$CHOSEN_FILE.pdf"
    exit 0
fi
