#!/usr/bin/env bash

OPTION=$(echo -e "monitor\nkeys\nwallpaper" | rofi -dmenu -i -p "hoorcolleges of oefenzittingen" -theme $HOME/dotfiles/rofi/black-white-selector.rasi)

case "$OPTION" in
    "keys")
        swapcaps
        ;;
    "monitor")
        displayselect
        ;;
    "wallpaper")
        wallpaper
        ;;
esac
