#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/uni/ ~/uni/bachelor-1/ ~/uni/bachelor-1/semester-1/ ~/uni/bachelor-1/semester-2/ ~/coding/ ~/Documents/ ~/repos ~/suckless/ ~/uni/bachelor-1/semester-1/calculus-1/lesmateriaal/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
tmux set-environment -t $selected_name TMUX_SESSION_ROOT "$selected"
