#!/usr/bin/env bash

OPTION=$(echo -e "picasso\nstantoncity\nstantonvalluga\njapanpow\noff" | rofi -dmenu -i -p "wallpaper" -theme $HOME/dotfiles/rofi/black-white-selector.rasi)

if [ -z "$OPTION" ]; then
    exit 1
fi

case "$OPTION" in
"picasso")
    feh --no-fehbg --bg-scale '/home/junot/dotfiles/wallpaper/wallpaper.jpg'
    ;;
"stantoncity")
    feh --no-fehbg --bg-scale '/home/junot/dotfiles/wallpaper/stantoncity.jpg'
    ;;
"stantonvalluga")
    feh --no-fehbg --bg-scale '/home/junot/dotfiles/wallpaper/stantonbeluga.jpg'
    ;;
"japanpow")
    feh --no-fehbg --bg-scale '/home/junot/dotfiles/wallpaper/japanpowder.jpg'
    ;;
"off")
    feh --no-fehbg --bg-scale '/home/junot/dotfiles/wallpaper/black.png'
    ;;
esac
