#!/usr/bin/env bash

OPTION=$(echo -e "planning\nfront-end\ncomputer systems\ndbf\npicasso\nstantoncity\nstantonvalluga\njapanpow\noff" | fuzzel --dmenu -i -p "wallpaper")

if [ -z "$OPTION" ]; then
  exit 1
fi

case "$OPTION" in
"planning")
  swaybg -i '/home/junot/hogeschool/bach1/sem1/planning/overzicht.png'
  ;;
"front-end")
  swaybg -i '/home/junot/hogeschool/bach1/sem1/planning/front-end.png'
  ;;
"computer systems")
  swaybg -i '/home/junot/hogeschool/bach1/sem1/planning/cs.png'
  ;;
"dbf")
  swaybg -i '/home/junot/hogeschool/bach1/sem1/planning/dbf.png'
  ;;
"picasso")
  swaybg -i '/home/junot/dotfiles/wallpaper/wallpaper.jpg'
  ;;
"stantoncity")
  swaybg -i '/home/junot/dotfiles/wallpaper/stantoncity.jpg'
  ;;
"stantonvalluga")
  swaybg -i '/home/junot/dotfiles/wallpaper/stantonbeluga.jpg'
  ;;
"japanpow")
  swaybg -i '/home/junot/dotfiles/wallpaper/japanpowder.jpg'
  ;;
"off")
  swaybg -i '/home/junot/dotfiles/wallpaper/black.png'
  ;;
esac
exit 0
