import= ["/home/junot/.config/alacritty/gruvbox_dark.toml"] 


[env]
TERM = "xterm-256color"


[font]
# normal = {family = "UbuntuMono Nerd Font", style = "Regular"}
# normal = {family = "JetBrains Mono Nerd Font", style = "Regular"}
normal = {family = "FiraCode Nerd Font", style = "Regular"}
size = 17


[window]
padding.x = 9
padding.y = 9

decorations = "None"
# opacity = 0.8k
