[font]
normal = {family = "FiraCode Nerd Font", style = "Regular"}
bold = {family = "FiraCode Nerd Font", style = "Bold"}
italic = {family = "FiraCode Nerd Font", style = "Italic"}
size = 12

# [window]
# padding.x = 9
# padding.y = 9
