# import= ["/home/junot/.config/alacritty/gruvbox_dark.toml"] 
import= ["/home/junot/.config/alacritty/gruvbox.toml"] 


[env]
TERM = "xterm-256color"


[font]
normal = {family = "LigaSFMonoNerdFont", style = "Regular"}
bold = {family = "LigaSFMonoNerdFont", style = "Bold"}
italic = {family = "LigaSFMonoNerdFont", style = "Italic"}
size = 15


[window]
padding.x = 9
padding.y = 9
