[font]
normal = {family = "FiraMono Nerd Font", style = "Regular"}
bold = {family = "FiraMono Nerd Font", style = "Regular"}
italic = {family = "FiraMono Nerd Font", style = "Italic"}
size = 15

[window]
padding.x = 9
padding.y = 9
