[colors.primary]
background = '#1d2021'
# background= '#282828'
# background= '#0E1018'
foreground= '#ebdbb2'

[colors.normal]
black =   '#282828'
red =     '#cc241d'
green=   '#98971a'
yellow=  '#d79921'
blue=    '#458588'
magenta= '#b16286'
# cyan =   '#98971a'
cyan=    '#689d6a'
# white=   '#a89984'
white= "#dfaf87"

[colors.bright]
black=   '#928374'
red=     '#fb4934'
green=   '#b8bb26'
yellow=  '#fabd2f'
blue=    '#83a598'
magenta= '#d3869b'
cyan=    '#8ec07c'
white=   '#ebdbb2'


[env]
TERM = "xterm-256color"


[font]
normal = {family = "LigaSFMonoNerdFont", style = "Regular"}
bold = {family = "LigaSFMonoNerdFont", style = "Bold"}
italic = {family = "LigaSFMonoNerdFont", style = "Italic"}
size = 15


[window]
padding.x = 9
padding.y = 9
